version: '3.7'
services:
  web:
    build: ./api-fois
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api-fois/:/usr/src/api-fois/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app_main
      - POSTGRES_PASSWORD=app_main
      - POSTGRES_DB=app_main_dev

volumes:
  postgres_data: